# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppr < Formula
  desc "ppr - CLI tool for creating themed wallpapers from SVG templates"
  homepage "https://github.com/byteowlz/ppr"
  version "1.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/byteowlz/ppr/releases/download/1.0.5/ppr_1.0.5_darwin_amd64.tar.gz"
      sha256 "fe03dc0a7e1231743ecf64f2eb18558b911e2225b5a3568279a31eab0d127e90"

      def install
        bin.install "ppr"
      end
    end
    on_arm do
      url "https://github.com/byteowlz/ppr/releases/download/1.0.5/ppr_1.0.5_darwin_arm64.tar.gz"
      sha256 "192e3dd0fb92ede43c736373fc3031af0d784a48956bce2122af1405911cb26e"

      def install
        bin.install "ppr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/byteowlz/ppr/releases/download/1.0.5/ppr_1.0.5_linux_amd64.tar.gz"
        sha256 "bdf4fbc9a6e11964089220e078e783b5532706c5741adf9b82faef52a70510ea"

        def install
          bin.install "ppr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/byteowlz/ppr/releases/download/1.0.5/ppr_1.0.5_linux_arm64.tar.gz"
        sha256 "a1f4204161570ce26ddfe4ccf54f51e5cc7f6d24224bf35c5b1a48263875b8eb"

        def install
          bin.install "ppr"
        end
      end
    end
  end

  test do
    system "#{bin}/ppr version"
  end
end
