# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppr < Formula
  desc "ppr - CLI tool for creating themed wallpapers from SVG templates"
  homepage "https://github.com/byteowlz/ppr"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteowlz/ppr/releases/download/1.2.0/ppr_1.2.0_darwin_amd64.tar.gz"
      sha256 "80b1e218e07273cd5bd32199eb86eb61cd83dd95d2bb339888b68a217d33bafe"

      def install
        bin.install "ppr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteowlz/ppr/releases/download/1.2.0/ppr_1.2.0_darwin_arm64.tar.gz"
      sha256 "9eec17ff1bb2cce02dd229086442bbacf5d50d3174f943128cd274699acf039e"

      def install
        bin.install "ppr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/ppr/releases/download/1.2.0/ppr_1.2.0_linux_amd64.tar.gz"
      sha256 "f8ed9ea5c6866fe85cc18a7bfbd9d7a356631b94ff5edfff9f8b133f645a381e"
      def install
        bin.install "ppr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/ppr/releases/download/1.2.0/ppr_1.2.0_linux_arm64.tar.gz"
      sha256 "99990ab17e6cffc5f89c2e539bf9b3a6e082313aadf0edfe31e611f6516ae7a9"
      def install
        bin.install "ppr"
      end
    end
  end

  test do
    system "#{bin}/ppr version"
  end
end
