# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppr < Formula
  desc "ppr - CLI tool for creating themed wallpapers from SVG templates"
  homepage "https://github.com/byteowlz/ppr"
  version "1.0.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/byteowlz/ppr/releases/download/1.0.8/ppr_1.0.8_darwin_amd64.tar.gz"
      sha256 "eeb8988670263b7f99959fab01e98f096742478aa116719eb5d87f7f2d06ac60"

      def install
        bin.install "ppr"
      end
    end
    on_arm do
      url "https://github.com/byteowlz/ppr/releases/download/1.0.8/ppr_1.0.8_darwin_arm64.tar.gz"
      sha256 "d11657957bd4f821a1896879112b5c66881f04860e9583b2a7a19b9a61d0fded"

      def install
        bin.install "ppr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/byteowlz/ppr/releases/download/1.0.8/ppr_1.0.8_linux_amd64.tar.gz"
        sha256 "c077939ac2ad1299421c13ea25c0f6acec3923357340fc70e32303e12203805f"

        def install
          bin.install "ppr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/byteowlz/ppr/releases/download/1.0.8/ppr_1.0.8_linux_arm64.tar.gz"
        sha256 "21c78144c2e460e91064c5065a7f750556929c41cd2147eac18f0e0d88d6f1a8"

        def install
          bin.install "ppr"
        end
      end
    end
  end

  test do
    system "#{bin}/ppr version"
  end
end
