# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrpr < Formula
  desc "A fast CLI for extracting main content from websites"
  homepage "https://github.com/byteowlz/scrpr"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Darwin_x86_64.tar.gz"
      sha256 "3b9841bbd66dd039be9bbf1b3f302db1aeb5d7c2d1347a36b6829fd8cc64397c"

      def install
        bin.install "scrpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Darwin_arm64.tar.gz"
      sha256 "510a815121a01872dc7ec0b7af4558f2c02f55d0e8f2a5d8408371d5e441118f"

      def install
        bin.install "scrpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Linux_x86_64.tar.gz"
      sha256 "3a90bee68451f69761921081200e27dbe38de127c7238097b6087127e7c3278b"
      def install
        bin.install "scrpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Linux_arm64.tar.gz"
      sha256 "299ab40a69fee73dc9e489be8e6c44b6b41ac445b92d74d0307f7b46a5f4e8ff"
      def install
        bin.install "scrpr"
      end
    end
  end

  test do
    system "#{bin}/scrpr", "--version"
  end
end
