# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrpr < Formula
  desc "A fast CLI for extracting main content from websites"
  homepage "https://github.com/byteowlz/scrpr"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Darwin_x86_64.tar.gz"
      sha256 "9c34501594352e40c8ca8f1e906fecc003092e4a1aa1b203aeb9468684d99cad"

      def install
        bin.install "scrpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Darwin_arm64.tar.gz"
      sha256 "e17e1614c6f82501ab83bf0e4ce0be0702fa62953d2dd85b8520e8e87d694e65"

      def install
        bin.install "scrpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Linux_x86_64.tar.gz"
      sha256 "f3d2848ab5a7e8a0320c504e4cbce03011b7b378043f7c5eac278d0f90cc3c8d"
      def install
        bin.install "scrpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Linux_arm64.tar.gz"
      sha256 "42a7169a5482195fdf232725a97b9523f6f7b2bc5d9eb9445b9d4d8765fc8899"
      def install
        bin.install "scrpr"
      end
    end
  end

  test do
    system "#{bin}/scrpr", "--version"
  end
end
