# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrpr < Formula
  desc "A fast CLI for extracting main content from websites"
  homepage "https://github.com/byteowlz/scrpr"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Darwin_x86_64.tar.gz"
      sha256 "5561c0c6f8d5fd82d69f10706c8cdc1de83e4e98e277e64524c161a23ef8b6b6"

      def install
        bin.install "scrpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Darwin_arm64.tar.gz"
      sha256 "6f9d5ded12b4f790e79f85c1714cdf663d27e6f88e0ae0cfdce226fad3b2dd7f"

      def install
        bin.install "scrpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Linux_x86_64.tar.gz"
      sha256 "821e98ce82041a1c452ea7ca320d817e23336d6824c18b7c95f44dac0a1cf49f"
      def install
        bin.install "scrpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/scrpr/releases/download/v1.1.0/scrpr_Linux_arm64.tar.gz"
      sha256 "1c2b2b4c6cc272a9180f6e2a21e66c237d139860db5c7e3a2ec8f8a1a8f74cef"
      def install
        bin.install "scrpr"
      end
    end
  end

  test do
    system "#{bin}/scrpr", "--version"
  end
end
