# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sx < Formula
  desc "Multi-engine web search from the command line"
  homepage "https://github.com/byteowlz/sx"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Darwin_x86_64.tar.gz"
      sha256 "668a3d6b697e998d25d0e06d5dc1b438690aa253f08d9e5451e60ebe5f5a1276"

      def install
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Darwin_arm64.tar.gz"
      sha256 "1756b802157b02006c291803c27868c562ae60354a527813217298df279db8f7"

      def install
        bin.install "sx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Linux_x86_64.tar.gz"
      sha256 "8b4b78dbf446c2441a35d66efbe982b7e4cda34f2adfa572d62ff323a006ff0d"
      def install
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Linux_arm64.tar.gz"
      sha256 "91bedc5c3a94e3453c4e235e7fbb60e0230c0f9a00511083616d69d895a394cd"
      def install
        bin.install "sx"
      end
    end
  end

  test do
    system "#{bin}/sx", "--version"
  end
end
