# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sx < Formula
  desc "Multi-engine web search from the command line"
  homepage "https://github.com/byteowlz/sx"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Darwin_x86_64.tar.gz"
      sha256 "5d84498c7faa9c5fe6e206ef9fc96dd8b164877b0a331620d7c3b118efe69e3c"

      def install
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Darwin_arm64.tar.gz"
      sha256 "58c34cd138d28204aff5c6fcc977e311c61bfae7b6b0a140109f4af416418949"

      def install
        bin.install "sx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Linux_x86_64.tar.gz"
      sha256 "fbb749fb253a5919c30f986840b4a1e0ff5734d0c398270d4a51dcbc2f3924d4"
      def install
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/sx/releases/download/v2.1.0/sx_Linux_arm64.tar.gz"
      sha256 "d134af142d74c8c9d40e6eb551038ea20050773519fc207f393d56046ca68372"
      def install
        bin.install "sx"
      end
    end
  end

  test do
    system "#{bin}/sx", "--version"
  end
end
