# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sx < Formula
  desc "Multi-engine web search from the command line"
  homepage "https://github.com/byteowlz/sx"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteowlz/sx/releases/download/v2.3.0/sx_Darwin_x86_64.tar.gz"
      sha256 "1b3cbf1008944c76024d59a7b276a08fd1b1f266b9c90800de3793ad977b1654"

      define_method(:install) do
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteowlz/sx/releases/download/v2.3.0/sx_Darwin_arm64.tar.gz"
      sha256 "7ebc2e7dcea0bd8270f5427e42c6a9fc57951a08e8044dd40ee744c1870ed29e"

      define_method(:install) do
        bin.install "sx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/sx/releases/download/v2.3.0/sx_Linux_x86_64.tar.gz"
      sha256 "e2438b0edb27e8de5a30c7b7b608ddbf3e5da57a5efa61f13288c83fdfc2b2cc"
      define_method(:install) do
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteowlz/sx/releases/download/v2.3.0/sx_Linux_arm64.tar.gz"
      sha256 "5ac6dd004b744419ccee1fbd38eaea3154bb3fb544f102f819cfb9b6ac4d2c7a"
      define_method(:install) do
        bin.install "sx"
      end
    end
  end

  test do
    system "#{bin}/sx", "--version"
  end
end
